version: "3.5"

services:
    redis:
        image: redis
        ports:
            - "6379:6379"

    app:
        build: .
        command: "serve"
        ports:
            - "1234:8000"
        depends_on:
            - redis
        environment:
            - REDIS_URL=redis://redis:6379
